import { NextResponse } from "next/server";
import * as XLSX from "xlsx";
import { requireAutomationKey } from "@/lib/automation-auth";
import { createErrorResponse } from "@/lib/api-handler";
import {
  ROW_HEADERS,
  buildVoucherXml,
  buildEnvelope,
  buildMastersXml,
  xmlEsc,
  type TallyRow,
  type VoucherSettings,
} from "@/lib/tally-xml";

// Server-side twin of the browser tool's export step. Same ROW_HEADERS, same builders from
// @/lib/tally-xml, so the register this returns is column-identical to the one a CA gets by
// clicking through /tools/invoice-to-tally.

const DEFAULT_SETTINGS: VoucherSettings = {
  company: "",
  voucherType: "Purchase",
  purchaseLedger: "Purchase Account",
  salesLedger: "Sales Account",
  cgstLedger: "Input CGST",
  sgstLedger: "Input SGST",
  igstLedger: "Input IGST",
  roundOffLedger: "Round Off",
};

/** Accepts either a full TallyRow or the invoice shape /api/classify-document returns. */
type RowInput = Partial<Record<keyof TallyRow, unknown>> & {
  fileName?: unknown;
  invoice?: Record<string, unknown>;
} & Record<string, unknown>;

function toRow(input: RowInput, index: number): TallyRow {
  const inv: Record<string, unknown> = input?.invoice ?? input;
  return {
    id: index + 1,
    File_Name: String(input.File_Name ?? input.fileName ?? ""),
    Invoice_Number: String(input.Invoice_Number ?? inv.billNumber ?? ""),
    Invoice_Date: String(input.Invoice_Date ?? inv.date ?? ""),
    Supplier_Name: String(input.Supplier_Name ?? inv.vendorName ?? ""),
    Supplier_GSTIN: String(input.Supplier_GSTIN ?? inv.gstin ?? ""),
    Taxable_Amount: String(input.Taxable_Amount ?? inv.taxableAmount ?? ""),
    CGST_Amount: String(input.CGST_Amount ?? inv.cgst ?? "0"),
    SGST_Amount: String(input.SGST_Amount ?? inv.sgst ?? "0"),
    IGST_Amount: String(input.IGST_Amount ?? inv.igst ?? "0"),
    Total_Amount: String(input.Total_Amount ?? inv.totalBillAmount ?? ""),
    Party_Ledger: String(input.Party_Ledger ?? ""),
    _src: String(input._src ?? "automation"),
    _warn: "",
  };
}

function buildHtml(rows: TallyRow[], warnings: string[]) {
  const head = ROW_HEADERS.map(h => `<th>${xmlEsc(h.replace(/_/g, " "))}</th>`).join("");
  const body = rows
    .map(r => `<tr>${ROW_HEADERS.map(h => `<td>${xmlEsc(r[h as keyof TallyRow] ?? "")}</td>`).join("")}</tr>`)
    .join("\n    ");
  const warnBlock = warnings.length
    ? `<div class="warn"><strong>${warnings.length} row(s) need attention</strong><ul>${warnings
        .map(w => `<li>${xmlEsc(w)}</li>`)
        .join("")}</ul></div>`
    : "";

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Invoice Register — NumberIQ</title>
<style>
 body{font:14px/1.5 system-ui,sans-serif;margin:2rem;color:#111}
 h1{font-size:1.25rem;margin:0 0 .25rem}
 p.sub{color:#666;margin:0 0 1.5rem}
 .scroll{overflow-x:auto}
 table{border-collapse:collapse;width:100%;min-width:900px}
 th,td{border:1px solid #ddd;padding:.4rem .6rem;text-align:left;white-space:nowrap}
 th{background:#f5f5f5;font-weight:600}
 tr:nth-child(even) td{background:#fafafa}
 .warn{background:#fff6e5;border:1px solid #f0c36d;padding:.75rem 1rem;border-radius:6px;margin-bottom:1.5rem}
 .warn ul{margin:.5rem 0 0 1rem;padding:0}
</style></head><body>
 <h1>Invoice Register</h1>
 <p class="sub">${rows.length} invoice(s) · generated by NumberIQ · review before importing into Tally</p>
 ${warnBlock}
 <div class="scroll"><table>
  <thead><tr>${head}</tr></thead>
  <tbody>
    ${body}
  </tbody>
 </table></div>
</body></html>`;
}

export async function POST(req: Request) {
  const denied = requireAutomationKey(req);
  if (denied) return denied;

  try {
    const body = await req.json();
    const input = Array.isArray(body) ? body : body.rows;

    if (!Array.isArray(input) || input.length === 0) {
      return createErrorResponse("bad_request", "Expected a non-empty rows array", 400);
    }

    const settings: VoucherSettings = { ...DEFAULT_SETTINGS, ...(body.settings ?? {}) };
    const rows = input.map(toRow);

    const warnings: string[] = [];
    const vouchers: string[] = [];
    let skipped = 0;

    rows.forEach(r => {
      const { xml, warn } = buildVoucherXml(r, settings);
      const who = r.Invoice_Number || r.File_Name || `row ${r.id}`;
      if (warn) warnings.push(`${who}: ${warn}`);
      if (xml) vouchers.push(xml);
      else skipped++;
    });

    const aoa = [ROW_HEADERS, ...rows.map(r => ROW_HEADERS.map(h => r[h as keyof TallyRow] ?? ""))];
    const ws = XLSX.utils.aoa_to_sheet(aoa);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "Invoice Register");
    const xlsxBase64 = XLSX.write(wb, { type: "base64", bookType: "xlsx" });

    const masters = buildMastersXml(rows, settings);

    return NextResponse.json({
      success: true,
      xlsxBase64,
      html: buildHtml(rows, warnings),
      xml: buildEnvelope(vouchers.join(""), settings.company, "Vouchers"),
      mastersXml: masters.xml,
      warnings,
      counts: { rows: rows.length, vouchers: vouchers.length, skipped, ledgers: masters.count },
    });
  } catch (error) {
    console.error("Error building Tally export:", error);
    return createErrorResponse("export_failed", (error instanceof Error ? error.message : "") || "Failed to build Tally export", 500);
  }
}
